# deploy/keycloak/config/example-kc.yaml

apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: example-kc
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: "humble-space-lamp-97p5g7gj65g6hx57w-8888.app.github.dev"
    strict: false
  proxy:
    headers: xforwarded
  additionalOptions:           # <-- Add this block
    - name: http-relative-path
      value: /auth
    