# deploy/charts/v2-service/templates/application.yaml
{{ include "common.deployment" . }}
---
{{ include "common.service" . }}
---
{{ include "common.httproute" . }}
---
{{ include "common.protected-route" . }}
---
{{ include "common.security-policy" . }}