# deploy/charts/v2-service/values.yaml
replicaCount: 1
image:
  repository: v2-service
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 8080

gateway:
  name: eg
  namespace: default
  path: /v2-service

protectedRoute:
  enabled: true
  # Note: we use /secure here just to show it's completely configurable!
  path: /secure

jwtAuth:
  enabled: true
  issuer: "https://humble-space-lamp-97p5g7gj65g6hx57w-8888.app.github.dev/auth/realms/master"
  remoteJwksUri: "http://example-kc-service.keycloak.svc.cluster.local:8080/auth/realms/master/protocol/openid-connect/certs"